/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/journal` | `/journal`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/map` | `/map`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore/essentials` | `/explore/essentials`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore/events` | `/explore/events`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore/food` | `/explore/food`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore/hikes` | `/explore/hikes`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/journal` | `/journal`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/map` | `/map`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore/essentials` | `/explore/essentials`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore/events` | `/explore/events`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore/food` | `/explore/food`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore/hikes` | `/explore/hikes`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/journal${`?${string}` | `#${string}` | ''}` | `/journal${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/map${`?${string}` | `#${string}` | ''}` | `/map${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore/essentials${`?${string}` | `#${string}` | ''}` | `/explore/essentials${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore/events${`?${string}` | `#${string}` | ''}` | `/explore/events${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore/food${`?${string}` | `#${string}` | ''}` | `/explore/food${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore/hikes${`?${string}` | `#${string}` | ''}` | `/explore/hikes${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/journal` | `/journal`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/map` | `/map`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore/essentials` | `/explore/essentials`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore/events` | `/explore/events`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore/food` | `/explore/food`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore/hikes` | `/explore/hikes`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
